### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by esolares** [jgurtowski/ectools#1]
I'm getting the following error:

  File "/data/users/solarese/bin/ectools/pb_correct.py", line 12, in <module>
    from cov import getMarkedRanges
  File "/data/users/solarese/bin/ectools/cov.py", line 3, in <module>
    from itertools import repeat,count,compress
ImportError: cannot import name compress

I can manually go into python and import " from itertools import repeat,count,compress" with no issues but for somereason when it is called from cov import getMarked Ranges, there is an error.

**Comment by esolares** [comment]
I have figured out the problem. I had to add ectools to my python path and also modify some of the headers of the files to point to the correct python environment.

**Comment by lurebgi** [comment]
Hi, could you please indicate how did you add ectools to your python path, and what to modify?

**Comment by lurebgi** [comment]
And which version of python did you use? Thanks

**Comment by lurebgi** [comment]
Now I solved the issue by using python 2.7.8
