### ISSUE TITLE
Conflict between file generated by partition.py and requirements by correct.sh

### ISSUE THREAD

**Issue by konrad** [jgurtowski/ectools#3]
After running 
`python ${ECTOOLS_HOME}/partition.py 20 500 pbreads.legnth_filtered.fa`
I change into the newly created folder `0001/` and run `sh ../correct.sh`. The following error is raised:

```
`ERROR: The following critical files could not be used
<TEST_PATH>/0001/p0000
Check your paths and file permissions and try again
```

The file `p0000` was not created. When I rename `p0500` to `p0000` this error does not occur.

**Comment by jgurtowski** [comment]
Hi Konrad,

You need to run ectools through grid engine or using the parallel command
fiund in the Readme. The files are supposed to start at p0001.

Good luck,
James

**Comment by konrad** [comment]
Thanks, James. Missed that part. I used parallel now to run ´correct.sh´ and it seems to work. Sorry, for the false alarm.
